### ISSUE TITLE
Display issue on Arch 4.12.13-1-ARCH

### ISSUE THREAD

**Issue by hexxxx** [uoaerg/wavemon#41] opened 2017-10-02 01:56 UTC
New issue with wavemon display in terminal emulator (termite) as well as TTY. Have never had an issue displaying wavemon previously. Wavemon loads and displays text data, but the percentage bars showing network strength do not display properly; they show maybe one or two '=' signs along the bar, towards the right (i.e. 100%) side, but not along the rest of the bar. 

ncurses = reinstalled,
wavemon = reinstalled, 
multiple term. emulators have been tried. 

Any advice? Thanks!

Image attached. 
![wavemon](https://user-images.githubusercontent.com/12835780/31061893-6d3db6de-a6f3-11e7-99c1-394aa45aa5ad.jpg)

**Comment by grrtrr** [comment] 2017-10-02 04:25
I wonder if this is a duplicate of #39 - which had the same problem with the bars on an xfce4-terminal. Can you please have a look to see -- if yes, the cause seems to be a recent Arch issue.

**Comment by mr-blobbyyy** [comment] 2017-10-11 10:14
I haven't checked in for a while, and the issue seems to be cleared up for me (still on xfce.) Too many things updated since I last checked wavemon, so I can't pin down a specific update that fixed my issue. Might have been that gnome update we got a couple days ago, who knows. xfce4-terminal and ncurses hasn't changed. kernel: 4.13.4-1

**Comment by grrtrr** [comment] 2018-01-27 20:36
I haven't heard back since October. If this is still a problem, please reopen.

**Closed by grrtrr** 2018-01-27 20:36 UTC
