### ISSUE TITLE
F3 ('scan') does not show any found devices/cells

### ISSUE THREAD

**Issue by fabaff** [uoaerg/wavemon#1] opened 2014-03-12 12:15 UTC
Please check the origial report at https://bugzilla.redhat.com/show_bug.cgi?id=1062931

"Start 'wavemon', then press F3 to 'scan'. The screen shows 'waiting for scan data ...', then after a few seconds it shows 'Waiting for scan data on wlp0s2f1u2 ...'. It remains like that for ages - I left it for around 30 minutes, then stopped the program.
('wlp0s2f1u2' is my wireless device, so it detected that correctly.)"

**Comment by grrtrr** [comment] 2015-10-31 19:11
I was unable to reproduce this issue, and have not heard a similar report. Since the above bug has been closed due to end-of-life, closing issue.

If problem persists, please open new issue.

**Closed by grrtrr** 2015-10-31 19:11 UTC
