### ISSUE TITLE
linking against ncurses 6.2 fails

### ISSUE THREAD

**Issue by rdvrey** [uoaerg/wavemon#91] opened 2021-02-10 11:36 UTC
Make fails at the linking stage. The libraries of ncurses are split in two: ncurses and ltinfo.
Solution add "-ltinfo" to the link commandline in the makefile.

regards,

Robert

**Comment by grrtrr** [comment] 2021-02-15 22:47
This is a duplicate of #89 where the same problem happened. A fix is on the way, please see there.

**Closed by grrtrr** 2021-02-15 22:47 UTC
